#!/usr/bin/env bash

set -euxo pipefail

OPENSSL_REPO_URL="https://github.com/openssl/openssl"
OPENSSL_VER="openssl-3.3.1"

BUILD_DIR=".build"
INSTALL_DIR="/opt/openssl"
OUT_DIR=".out"

NICE="nice -19 ionice -c2 -n5"

build_time="$(date '+%Y%m%d%H%M%S')"

function abspath() {
  readlink -m "$1"
}

write_version() {
  filepath="${1}"

  cat > "$filepath" << EOF
${OPENSSL_REPO_URL}
${OPENSSL_VER}
$(git rev-parse HEAD)
$(git describe --always --dirty)
$(git describe --always --dirty --tags)
$(git describe --always --dirty --tags --all)
${build_time}
EOF
}

build_dir="$(abspath ${BUILD_DIR})"
mkdir -p "${build_dir}"
outdir="$(abspath "${OUT_DIR}")"
mkdir -p "${outdir}"

pushd "$build_dir" >/dev/null
  src_dir="openssl-${OPENSSL_VER}"

  if [ ! -d "${src_dir}" ]; then
    git clone --recursive --depth=100 -b "${OPENSSL_VER}" "${OPENSSL_REPO_URL}" "${src_dir}"
  fi

  pushd "${src_dir}" >/dev/null
    ${NICE} ./config \
      --prefix="${INSTALL_DIR}" \
      --libdir="lib" \
      --openssldir="etc/openssl" \
      no-apps \
      no-dso \
      no-engine \
      no-shared \
      CFLAGS="-g0 -Os -fPIC --static -static -Bstatic ${CFLAGS:+:CFLAGS}" \
      CXXFLAGS="-g0 -Os -fPIC --static -static -Bstatic ${CXXFLAGS:+:CXXFLAGS}" \
      LDFLAGS="--static -static -static-libgcc ${LDFLAGS:+:LDFLAGS}" \

    ${NICE} make -j"$(nproc)" | tee -a "build.log" | stdbuf -oL grep --color=always -iE "error|fail|fail|cannot|can't|unable|$"
    ${NICE} make install_sw | tee -a "build.log" | stdbuf -oL grep --color=always -iE "error|fail|fail|cannot|can't|unable|$"

    write_version "${INSTALL_DIR}/version.txt"
    cp "build.log" "${INSTALL_DIR}/"
    tar -cf - -C "${INSTALL_DIR}" . | xz -T0 -9 > "${outdir}/${OPENSSL_VER}-static-${build_time}.tar.xz"
  popd >/dev/null
popd >/dev/null

